{
 "title": "Tuya Smart WiFi Plugs",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "ip",
    "query": {
     "query": "label_values(container_network_receive_packets_total{cluster=\".*\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tuya_cur_state" }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "tuya_cur_power" }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "tuya_cur_voltage" }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "tuya_cur_current" }
   ]
  }
 ]
}